### PR TITLE
Migrate to AWS SAM and sanitize input

### LINKED ISSUE #52: Severe security flaw: JS injection into wkhtmltopdf
Flaw found by Teeramaet Bongkodmalee.

## What happened?

Write this
```
<script>
x=new XMLHttpRequest;
x.onload=function(){document.body.innerHTML = this.responseText};
x.open("GET","file:///usr/src/app/cred.json");x.send();
</script>
```
and call the lambda using https://pdf.graders.me/editor.

The secret credential will be printed into the PDF.

## How to fix this?

I will sanitize/disable JS in wkhtmltopdf input before rendering.

## Severity

10/10. All secret credentials are leaked. (I accept it as my fault. It was my carelessness as a developer.)

Fixes will be made into v1.3.0 as soon as possible.

### PR DESCRIPTION
**Pull request by plumsirawit**
- Migrate out of serverless framework to AWS SAM instead.
- Sanitize markdown

This should fix #52.

### CODE REVIEW

**Comment by plumsirawit** [comment]
Currently the sanitizer is still not working as expected. It over-sanitized the input:
- LaTeX are scrambled all over the place.
- Tags are added in invalid places.

Example output:
image

I request @MasterIceZ, if possible, to take a look at the sanitizing process.

**Comment by plumsirawit** [comment]
Sanitizing is postponed. Currently the temporary solution is to disable file access. In the future I'm thinking of using `cgroups` to limit the permission given to the function.

**Comment by plumsirawit** [comment]
Currently ready for review. I feel like it's "stable enough" for now. Let me know if there is any problem.

**Review by MasterIceZ — APPROVED** [review]
lgtm

**Comment by plumsirawit** [comment]
I've already forgotten everything.

YOLO.

**Pull request merged**
